# Generated by Django 2.2.4 on 2020-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicantregistrationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('passworD', models.CharField(max_length=20)),
            ],
        ),
    ]
