# Generated by Django 2.2.4 on 2020-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantApllicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_ap_name', models.CharField(max_length=20)),
                ('ap_date_of_birth', models.DateField()),
                ('ap_email_id', models.EmailField(max_length=254)),
                ('ap_gender', models.CharField(max_length=20)),
                ('ap_mobileno', models.IntegerField(unique=True)),
                ('ap_address', models.CharField(max_length=30)),
                ('ap_post', models.CharField(max_length=30)),
                ('ap_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ap_resume', models.FileField(upload_to='resume_files/')),
            ],
        ),
    ]
