# Generated by Django 2.2.4 on 2020-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitmentm',
            fields=[
                ('o_code', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=30)),
                ('registration_start_from', models.DateField(verbose_name='yy-mm-dd')),
                ('age_limit', models.IntegerField()),
                ('lastdate_to_apply', models.DateField()),
                ('department_id', models.IntegerField()),
                ('no_of_position', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('responsibilities', models.CharField(max_length=30)),
                ('contactno', models.IntegerField(unique=True)),
            ],
        ),
    ]
