# Generated by Django 2.2.4 on 2020-02-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20200218_1938'),
        ('app', '0001_initial'),
        ('manager', '0002_auto_20200219_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewerschmodel',
            fields=[
                ('ap_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicant.ApplicantApllicationModel')),
                ('date', models.CharField(max_length=20)),
                ('select_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Adminmodel')),
            ],
        ),
    ]
